sources:
  - name: CZIDGQL
    handler:
      graphql:
        endpoint: ${API_URL}/graphql
        source: ./sources/czid-schema.graphql
        operationHeaders:
          Cookie: "{context.headers['cookie']}"
  - name: CZIDREST
    handler:
      jsonSchema:
        endpoint: ${API_URL}/
        operations:
          - type: Query
            field: AmrWorkflowResults
            path: /workflow_runs/{args.workflowRunId}/results
            method: GET
            responseSchema: ./json-schemas/amrWorkflowResults.json
            responseTypeName: AmrWorkflowResults
          - type: Query
            field: BulkDownload
            path: /bulk_downloads/{args.bulkDownloadId}
            method: GET
            responseSchema: ./json-schemas/bulkDownloads.json
            responseTypeName: BulkDownload
            headers:
              Cookie: "{context.headers['cookie']}"
          - type: Query
            field: ConsensusGenomeWorkflowResults
            path: /workflow_runs/{args.workflowRunId}/results
            method: GET
            responseSchema: ./json-schemas/consensusGenomeWorkflowResults.json
            responseTypeName: ConsensusGenomeWorkflowResults
          - type: Query
            field: PersistedBackground
            path: /persisted_backgrounds/{args.projectId}
            method: GET
            responseSchema: ./json-schemas/persistedBackground.json
            responseTypeName: PersistedBackground
            headers:
              Cookie: "{context.headers['cookie']}"
          - type: Query
            field: PipelineData
            path: /samples/{args.sampleId}/pipeline_viz/7.0.json
            method: GET
            responseSchema: ./json-schemas/pipelineData.json
            responseTypeName: PipelineData
            headers:
              Cookie: "{context.headers['cookie']}"
          - type: Query
            field: Samples
            path: /samples/index_v2.json?projectId={args.projectId}
            method: GET
            responseSchema: ./json-schemas/samples.json
            responseTypeName: Samples
          - type: Query
            field: TaxonDist
            path: /backgrounds/{args.backgroundId}/show_taxon_dist.json?taxid={args.taxonId}
            method: GET
            responseSchema: ./json-schemas/taxonDist.json
            responseTypeName: TaxonDist
            headers:
              Cookie: "{context.headers['cookie']}"
          - type: Query
            field: Background
            path: /pub/{args.snapshotShareId}/backgrounds.json
            method: GET
            responseSchema: ./json-schemas/snapshotBackground.json
            responseTypeName: Background
          - type: Mutation
            field: UpdateSampleNotes
            path: /samples/{args.sampleId}/save_metadata
            method: POST
            requestSample: {"value": "test", "field": "notes", "authenticityToken": "test"}
            responseSchema: ./json-schemas/updateSampleNotes.json
            responseTypeName: UpdateSampleNotes
            headers:
              Cookie: "{context.headers['cookie']}"
      transforms:
        - namingConvention:
            typeNames: camelCase
            fieldNames: camelCase
additionalResolvers:
  - ./resolvers.ts
serve:
  port: 4444
  endpoint: "/graphqlfed"
