version: "3.8"

services:
  gql:
    build:
      context: .
      dockerfile: Dockerfile
    image: "czid-graphql"
    platform: linux/arm64
    restart: always
    environment:
      API_URL: http://web:3001
      NEXTGEN_API_URL: http://web:8008
      LEGACY_API_URL: http://web:3001
      ALLOWED_CORS_ORIGINS: "http://web:3001,http://localhost:3000"
      NEXTGEN_ENTITIES_URL: "http://entities.czidnet:8008"
      NEXTGEN_WORKFLOWS_URL: "http://workflows.czidnet:8042"
    ports:
      - "4444:4444"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Use node_modules built in container, not from the mounted source dir
    networks:
      czidnet:
        aliases:
          - gql.czidnet.localdev
networks:
  czidnet:
    name: czidnet
    external: true
