on:
  release:
    types: [published]

name: Deploy main to staging
jobs:
  deploy-to-staging-env:
    runs-on: [ARM64, self-hosted, Linux]
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Assume happy-api deployment role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: CzidGraphQLFederationUpdateStaging
      - name: Install happy
        uses: chanzuckerberg/github-actions/.github/actions/install-happy@main
      - name: Set version info
        uses: chanzuckerberg/czid-graphql-federation-server/.github/actions/happy-config-set@main
        with:
          app_config_name: CZID_GQL_FED_GIT_SHA
          app_config_value: ${{ github.sha }}
          happy_env: staging
      - name: Set CZ ID Rails API URL
        uses: chanzuckerberg/czid-graphql-federation-server/.github/actions/happy-config-set@main
        with:
          app_config_name: API_URL
          app_config_value: ${{ vars.API_URL}}
          happy_env: staging
      - name: Set allowed CORS origins
        uses: chanzuckerberg/czid-graphql-federation-server/.github/actions/happy-config-set@main
        with:
          app_config_name: ALLOWED_CORS_ORIGINS
          app_config_value: ${{ vars.ALLOWED_CORS_ORIGINS}}
          happy_env: staging
      - name: Deploy to staging env
        uses: chanzuckerberg/github-actions/.github/actions/deploy-happy-stack@v1.26.0
        with:
          tfe-token: ${{ secrets.TFE_TOKEN }}
          env: ${{ vars.HAPPY_ENV }}
          create-tag: true
          stack-name: ${{ secrets.HAPPY_STACK_NAME }}
          version-lock-file: .happy/version.lock
