on:
  push:
    branches:
      - staging

name: Deploy staging branch to staging env
jobs:
  update-staging:
    runs-on: [ARM64, self-hosted, Linux]
    permissions:
      id-token: write
    steps:
      - name: Assume happy-api deployment role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          role-duration-seconds: 1200
          role-session-name: CzidGraphQLFederationUpdateStaging
      - name: Update staging
        uses: chanzuckerberg/github-actions/.github/actions/deploy-happy-stack@deploy-happy-stack-v1.12.0
        with:
          tfe-token: ${{ secrets.TFE_TOKEN }}
          env: staging
          create-tag: true
          stack-name: staging-stack
          happy-version: 0.92.0
      - name: Deployed branch and SHA
        run: echo "Deployed SHA $(git rev-parse HEAD) from $(git branch --show-current) branch"
