on:
  release:
    types: [published]

name: Update prod branch and deploy to prod env
jobs:
  deploy-to-prod-env:
    runs-on: [ARM64, self-hosted, Linux]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Assume happy-api deployment role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
          role-duration-seconds: 1200
          role-session-name: CzidGraphQLFederationUpdateProd
      - name: Deploy to production env
        uses: chanzuckerberg/github-actions/.github/actions/deploy-happy-stack@deploy-happy-stack-v1.13.0
        with:
          tfe-token: ${{ secrets.TFE_TOKEN }}
          env: prod
          create-tag: true
          stack-name: prod-stack
          happy-version: 0.92.0
