name: Deploy to sandbox env

on:
  push:
    branches:
       - sandbox
  workflow_dispatch:

jobs:
  deploy-to-sandbox-env:
    runs-on: [ARM64, self-hosted, Linux]
    environment: sandbox
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Assume happy-api deployment role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: CzidGraphQLFederationUpdateSandbox
      - name: Install happy
        uses: chanzuckerberg/github-actions/.github/actions/install-happy@main
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const id_token = await core.getIDToken()
            core.setOutput('id_token', id_token)
            core.exportVariable('id_token', id_token);
      - name: Set version info
        uses: chanzuckerberg/czid-graphql-federation-server/.github/actions/happy-config-set@sandbox
        with:
          env_var_name: CZID_GQL_FED_GIT_SHA
          env_var_value: ${{ github.sha }}
          happy_env: sandbox
      - name: Set CZ ID Rails API URL
        uses: chanzuckerberg/czid-graphql-federation-server/.github/actions/happy-config-set@sandbox
        with:
          env_var_name: API_URL
          env_var_value: ${{ vars.API_URL}}
          happy_env: sandbox
      - name: Set allowed CORS origins
        uses: chanzuckerberg/czid-graphql-federation-server/.github/actions/happy-config-set@sandbox
        with:
          env_var_name: ALLOWED_CORS_ORIGINS
          env_var_value: ${{ vars.ALLOWED_CORS_ORIGINS}}
          happy_env: sandbox
      - name: Update sandbox
        uses: chanzuckerberg/github-actions/.github/actions/deploy-happy-stack@v1.26.0
        with:
          tfe-token: ${{ secrets.TFE_TOKEN }}
          env: ${{ vars.HAPPY_ENV }}
          create-tag: true
          stack-name: ${{ secrets.HAPPY_STACK_NAME }}
          version-lock-file: .happy/version.lock
