name: Jest unit tests
on: push

jobs:
  jest-unit-tests:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - name: Install dependencies
        run: |
          sudo apt-get update
          apt-cache search libcurl
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Install modules
        run: |
          npm ci --verbose --no-optional
      - name: Run tests
        run: |
          npm test
